### ISSUE TITLE
doesn’t load in CarPlay environment

### ISSUE THREAD

**Issue by leonardo-79** [TortugaPower/BookPlayer#793] opened 2022-05-21 07:08 UTC
With the latest IOS something gas changes that made not working BookPlayer through CarPlay interface. You need ti open it throup the iPhone connected ti CarPlay And the non ti world. But often it crash.

**Comment by GianniCarlo** [comment] 2022-05-21 13:00
Carplay support was reworked in this PR → https://github.com/TortugaPower/BookPlayer/pull/775, the problem is that Apple hasn't approved yet our request for renewed CarPlay access to make use of the APIs introduced in iOS 14, so we can't release those updates yet (it's been over a month now), as soon as we get our approval we'll release the new changes

**Comment by GianniCarlo** [comment] 2022-06-05 19:23
This should be fixed in v4.6.0 which is now available in the appstore 👍. Feel free to write back if this is still happening in the latest version

**Closed by GianniCarlo** 2022-06-05 19:23 UTC
