### ISSUE TITLE
App crashes when opened

### ISSUE THREAD

**Issue by Erickallen** [TortugaPower/BookPlayer#678] opened 2021-11-04 18:59 UTC
## Environment

 - OS Version: iOS 15.1
 - App version 4.2.1
 - 
 app crashes on open

## Steps to reproduce the behavior
1. Open app
2. it crashes

**Comment by GianniCarlo** [comment] 2021-11-04 19:17
This is a possible duplicate of #672 and #665, the next build should fix this, it is live in TestFlight right now, and should be available in the AppStore in a few days

**Comment by GianniCarlo** [comment] 2021-11-16 13:38
closing this due to inactivity and possible duplicate of the issues mentioned before

**Closed by GianniCarlo** 2021-11-16 13:38 UTC
Labels: bug
