### ISSUE TITLE
Can't import files 

### ISSUE THREAD

**Issue by Doc-data** [TortugaPower/BookPlayer#855] opened 2022-11-04 15:09 UTC
I use it on ipad pro M1, I can't get it to import files from the local files it freezes and the app closes

**Comment by GianniCarlo** [comment] 2022-11-07 13:33
Hi @Doc-data , when you import, do you do it from within the app? I've managed to reproduce one case on my ipad mini, and when you long press on the app in the home screen, you'll get a list of files that you could potentially import, but it fails and crashes due to the file not being available locally (usually these are suggestions from the Files app, and the files are not always downloaded)

**Comment by GianniCarlo** [comment] 2023-07-11 22:46
I'm closing this ticket now that we have native iPad support with v5.0.0, feel free to post back if the issue continues and we can reopen the ticket

**Closed by GianniCarlo** 2023-07-11 22:46 UTC
