### ISSUE TITLE
Bug: ...double / triple catalogue entries

### ISSUE THREAD

**Issue by a-oe** [TortugaPower/BookPlayer#920] opened 2023-06-19 17:11 UTC
## BookPlayer on iPhone 

 - OS Version: [iOS 16.5]
 - App Version: [5.0]

## After importing new audiobooks via computer / USB, some library entries are double ore even triple in list
No iCloud connection (iCloud disabled).

## Steps to reproduce the behavior
1. Copy files via USB from Desktop Computer
2. View list of audiobooks in app
3. Mostly the last entrie are double. Sort order makes no difference.

**Comment by GianniCarlo** [comment] 2023-06-20 05:20
This looks to be related to #915 and a failed migration from the store, I'm copy / pasting my findings:

I was able to reproduce this issue. After a failed migration, the CoreData stack ends up in bad place, and does not work reliably, for example when trying to display the next page of items, it's ignoring the offset of the already loaded items, and that's why it's duplicating items.

To force a failed migration, I created a new schema version (v10), and tested going from model v8 to v10 (model v9 was introduced in app version 5.0.0). It is coded in a way that it will apply each model/schema version at a time, and I found a bug, that after it finishes migrating to v9, I was trying to load the data store to perform custom actions and populate folder information, the problem is that the expected version of the store is v10, and it was just migrated to v9, that's where it fails. So in the AppStore version, one possible scenario is that users that are experiencing this bug, went from schema v7 to v9.

I'm testing for ways to recover from this state, probably go to the previous version and retry the migration, but in any case, what mckayfackrell posted in this ticket, it's a good solution

> Same issue for me. I was able to locate all the files if I searched in BookPlayer and in the files app on iPhone under the processed folder.
>
> I moved my book files to a new folder in the files app and deleted the BookPlayer app. I redownloaded the app and the only way to import that worked was by selecting the add files (plus button) in the BookPlayer app and manually selected the files.

**Comment by a-oe** [comment] 2023-06-20 14:50
Thanks! I'll post a "close with comment", after succesful update.

**Comment by GianniCarlo** [comment] 2023-06-20 23:26
@a-oe got a build on TestFlight live right now with a fix for this (link to join: https://testflight.apple.com/join/xLDneJXN), please let us know if it fixes your issue, just a heads-up, folders that may have previously disappeared due to the bug, may appear with blank details on first launch, but on subsequent app launches they'll be populated correctly

**Comment by a-oe** [comment] 2023-06-21 06:16
Quick test in TestFlight: 
2 audiobook files loaded via USB: Both are double in the list view.
Sorry, not fixed.
![grafik](https://github.com/TortugaPower/BookPlayer/assets/123296412/8c90da2c-cd50-4672-8e41-3fb7606e79cd)

**Comment by GianniCarlo** [comment] 2023-06-21 10:06
@a-oe can you help me with a screenshot of the contents of the Processed folder? On the Files app, go to On My iPhone, then BookPlayer and finally Processed. I want to verify if there's a folder in there that's not being rendered inside the app

**Comment by a-oe** [comment] 2023-06-21 10:17
IMG_2381.jpeg
IMG_2382.jpeg
View of the files on iOS in "Processed".
The "Karl Ove" audiobook has two parts; imported in one file. The shown folders contain the two parts each.
Also strange are the entries that use random characters and numbers.

**Comment by a-oe** [comment] 2023-06-21 15:33
The random numbers are other files.
The folders each contain the same two audio files.

**Closed** 2023-07-22 10:15 UTC
Labels: bug
