### ISSUE TITLE
Bug: Error AVPlayerItem-The operation could not be completed

### ISSUE THREAD

**Issue by Yookeroo** [TortugaPower/BookPlayer#1120] opened 2024-03-22 14:29 UTC
## Environment

 - OS Version: IOS 17.3.1
 - App Version: 5.2.6-44

## Description

I get the above error message when trying to play an audiobook 

## Steps to reproduce the behavior
1. Launch application 
2. Select a book
3. Push PLAY

Tried restarting my phone. Didn’t help.

**Comment by ysakols** [comment] 2024-04-30 23:32
+1

**Comment by jamesonBradfield** [comment] 2024-05-17 04:24
Same here, downloaded mp3s from Google drive imported them, and playing gives this
![image](https://github.com/TortugaPower/BookPlayer/assets/113628216/70307765-de86-4d49-85d2-744c6d29e7d4)
Seems to be only applicable to the first mp3 
![image](https://github.com/TortugaPower/BookPlayer/assets/113628216/b2a01b51-2606-4e00-885c-79542f2c8382)
im gonna try and reupload only the first and see if it’s something with the downloads.

**Comment by GianniCarlo** [comment] 2024-05-17 12:27
I've been trying to reproduce this issue but with no luck, @jamesonBradfield please let me know if it's consistently happening with the first file, if so, do you mind sharing that file with me? In the meantime, I'll include a more descriptive error code for the next version

**Comment by jamesonBradfield** [comment] 2024-05-17 14:48
Yeah, I can’t seem to upload via drive, I’ll send it via my pic when i get time.

**Comment by jamesonBradfield** [comment] 2024-05-17 20:04
Here it is, could it be that I tried to play it too early after transferring it from drive? [Bad Mp3?](https://drive.google.com/drive/folders/1Vx7FFNPrQhzBoa-RlUp1ljxbWARQluPs?usp=sharing)

**Comment by silaswanders** [comment] 2024-05-18 06:03
What are the odds. I’m having the exact issue, with this exact series. Everything plays except the first book there. The file plays in every other app and in Files/Finder too.

**Comment by ysakols** [comment] 2024-05-18 17:05
Same file for me too. This is too funny. Must be the file?

**Comment by silaswanders** [comment] 2024-05-18 17:09
I love that we're all trying to read the same book at the same time with the same files. It does play fine for me in Prologue. That being said, I'm going to re-encode it into an M4B anyway. I'll let you know if that works. @ysakols @jamesonBradfield

**Comment by jamesonBradfield** [comment] 2024-05-18 17:11
I haven’t tried that, maybe it could be an interim solution

**Comment by silaswanders** [comment] 2024-05-18 17:17
The metadata is all messed up anyway and the cover art is a little wack. I usually also combine the separate parts into a single chaptered M4B with custom artwork.

**Comment by silaswanders** [comment] 2024-05-18 20:31
> There's definitely something wrong with the encoding of the file, this is the result of running ffprobe on it. I'll see what else I can glimpse from the error codes in-app
> 
> <img alt="Screenshot 2024-05-18 at 12 22 15 PM" width="1064" src="https://private-user-images.githubusercontent.com/14112819/331819047-6f23ad82-b3d5-43d9-83b1-6119a183920f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjM3ODgsIm5iZiI6MTcxNjA2MzQ4OCwicGF0aCI6Ii8xNDExMjgxOS8zMzE4MTkwNDctNmYyM2FkODItYjNkNS00M2Q5LTgzYjEtNjExOWExODM5MjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIwMTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOGMwMzY4MmQzOWFjMGVlMTc1ZjkwZDQwZjBiYTY4YzcxOGQwNzk4YzhmNDdiNDcwYTZhZmEzYmMxY2IxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.av_9cUhWl7e8WkCeBsNTcXajIZsPHc7V3AYJ4EKj0kc">

Found the same thing. The track length/duration is off. It also has all the chapter breaks stripped (which isn't surprising, but at least the previous book had separate MP3s), and it didn't want to go into my encoder (throwing duration errors too).

Anyway, after a few hours, some encoding, manual metadata curating, some Photoshop and a library visit, I've fixed it. DM me for the debugged version.  The original file is junk, I'd throw it away. Not BookPlayer's fault.

<img width="659" alt="Screenshot 2024-05-18 at 4 19 52 PM" src="https://github.com/TortugaPower/BookPlayer/assets/11682626/f53eb2db-b682-488c-a47d-1e548115ca4a">
<img width="669" alt="Screenshot 2024-05-18 at 4 30 40 PM" src="https://github.com/TortugaPower/BookPlayer/assets/11682626/011f72bd-2e21-4554-af85-670559651ff0">

**Comment by jamesonBradfield** [comment] 2024-05-18 21:48
> > There's definitely something wrong with the encoding of the file, this is the result of running ffprobe on it. I'll see what else I can glimpse from the error codes in-app
> 
> > 
> 
> > <img alt="Screenshot 2024-05-18 at 12 22 15 PM" width="1064" src="https://private-user-images.githubusercontent.com/14112819/331819047-6f23ad82-b3d5-43d9-83b1-6119a183920f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjM3ODgsIm5iZiI6MTcxNjA2MzQ4OCwicGF0aCI6Ii8xNDExMjgxOS8zMzE4MTkwNDctNmYyM2FkODItYjNkNS00M2Q5LTgzYjEtNjExOWExODM5MjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIwMTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOGMwMzY4MmQzOWFjMGVlMTc1ZjkwZDQwZjBiYTY4YzcxOGQwNzk4YzhmNDdiNDcwYTZhZmEzYmMxY2IxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.av_9cUhWl7e8WkCeBsNTcXajIZsPHc7V3AYJ4EKj0kc">
> 
> 
> 
> Found the same thing. The track length/duration is off. It also has all the chapter breaks stripped (which isn't surprising, but at least the previous book had separate MP3s), and it didn't want to go into my encoder (throwing duration errors too).
> 
> 
> 
> Anyway, after a few hours, some encoding, manual metadata curating, some Photoshop and a library visit, [I've fixed it](https://www.dropbox.com/t/HTYcpaQj5y7t8upC). DM me for the debugged version.  The original file is junk, I'd throw it away. Not BookPlayer's fault.
> 
> 
> 
> <img width="659" alt="Screenshot 2024-05-18 at 4 19 52 PM" src="https://github.com/TortugaPower/BookPlayer/assets/11682626/f53eb2db-b682-488c-a47d-1e548115ca4a">
> 
> <img width="669" alt="Screenshot 2024-05-18 at 4 30 40 PM" src="https://github.com/TortugaPower/BookPlayer/assets/11682626/011f72bd-2e21-4554-af85-670559651ff0">
> 
> 
> 
> 
> 
> 

I don't think there's dm ing in GitHub😂,

**Comment by silaswanders** [comment] 2024-05-20 19:41
> I don't think there's dm ing in GitHub😂,
That is brilliant. I just assumed, sure, every platform has it, why not GitHub, thinking I just never saw it. Link is there though. Hope that fixes the issue with the file!

**Comment by GianniCarlo** [comment] 2024-05-27 05:32
Thanks everyone for your input on this ticket, the next version will have a more detailed error message, though for this case it doesn't add much tbh (see screenshot)

![IMG_4367](https://github.com/TortugaPower/BookPlayer/assets/14112819/b27ee7ff-cdf6-476d-8555-4b45363eef00)

**Closed by GianniCarlo** 2024-05-27 05:32 UTC
Labels: bug

**Comment by yutripn** [comment] 2024-06-13 16:06
> > I don't think there's dm ing in GitHub😂,
> 
> That is brilliant. I just assumed, sure, every platform has it, why not GitHub, thinking I just never saw it. Link is there though. Hope that fixes the issue with the file!

Hello! Your link to the fixed file expired… any chance you’d be willing to provide a new one? I’m having this exact issue 😂 thanks!
