### ISSUE TITLE
Bug: empty library after 5.0.0 update

### ISSUE THREAD

**Issue by s00d** [TortugaPower/BookPlayer#915] opened 2023-06-18 07:18 UTC
## Environment

 - OS Version: 16.5
 - App Version: 5.0.0

## Description

after the update, the application does not work, the library is empty. There are books in the search and in the settings you can see them, but the folder does not show. tried a lot of things, completely rewrote the books, nothing helps

## Steps to reproduce the behavior
1. Open app

![image](https://github.com/TortugaPower/BookPlayer/assets/2684895/900ec1f7-5adc-4461-9a22-d06d8c8db599)
![image](https://github.com/TortugaPower/BookPlayer/assets/2684895/563e061c-c688-47c7-a9d0-2b57c8c1b6d2)
![image](https://github.com/TortugaPower/BookPlayer/assets/2684895/ffb12d49-f604-4b06-bac6-87b0e6601bea)
![image](https://github.com/TortugaPower/BookPlayer/assets/2684895/c5a3ae3b-8b52-442e-9613-dccda5cd1902)

**Comment by s00d** [comment] 2023-06-18 07:26
Sometimes, when restarting the application, individual files started appearing in the library. When changing the sorting, you can also see 2-3 of them, but the program still doesn't function properly.

**Comment by s00d** [comment] 2023-06-18 07:54
I tried to reindex the library using iMazing, and I was initially relieved when the indexing process started. However, after it finished, all the books were placed in one folder, and a bunch of identical empty folders appeared in the library.

**Comment by GianniCarlo** [comment] 2023-06-18 12:01
thanks for reporting the issue @s00d and providing all the screenshots, I'm looking into it, when they appear on the search screen, do they work / start playback if you tap them?

**Comment by s00d** [comment] 2023-06-18 16:16
> thanks for reporting the issue @s00d and providing all the screenshots, I'm looking into it, when they appear on the search screen, do they work / start playback if you tap them? 

Yes

**Comment by mckayfackrell** [comment] 2023-06-18 17:39
Same issue for me. I was able to locate all the files if I searched in BookPlayer and in the files app on iPhone under the processed folder.

I moved my book files to a new folder in the files app and deleted the BookPlayer app. I redownloaded the app and the only way to import that worked was by selecting the add files (plus button) in the BookPlayer app and manually selected the files.

**Comment by cantonalex** [comment] 2023-06-19 06:14
Same for me stuff is all over the place.

**Comment by s00d** [comment] 2023-06-19 08:43
In general, I was able to transfer the books, but I encountered the following issues:

1. When transferring multiple folders, everything gets messed up. Now I'm transferring them one folder at a time (subfolders work fine).
2. After updating, my entire library disappeared. The problem may be related to the first error, so I had to completely clear the library and reinstall the application.

**Comment by GianniCarlo** [comment] 2023-06-20 05:18
I was able to reproduce this issue. After a failed migration, the CoreData stack ends up in bad place, and does not work reliably, for example when trying to display the next page of items, it's ignoring the offset of the already loaded items, and that's why it's duplicating items.

To force a failed migration, I created a new schema version (v10), and tested going from model v8 to v10 (model v9 was introduced in app version 5.0.0). It is coded in a way that it will apply each model/schema version at a time, and I found a bug, that after it finishes migrating to v9, I was trying to load the data store to perform custom actions and populate folder information, the problem is that the expected version of the store is v10, and it was just migrated to v9, that's where it fails. So in the AppStore version, one possible scenario is that users that are experiencing this bug, went from schema v7 to v9.

I'm testing for ways to recover from this state, probably go to the previous version and retry the migration, but in any case, what @mckayfackrell posted in this ticket, it's a good solution

> Same issue for me. I was able to locate all the files if I searched in BookPlayer and in the files app on iPhone under the processed folder.
>
> I moved my book files to a new folder in the files app and deleted the BookPlayer app. I redownloaded the app and the only way to import that worked was by selecting the add files (plus button) in the BookPlayer app and manually selected the files.

**Comment by GianniCarlo** [comment] 2023-06-20 14:36
following up on this, when the migration fails, the fields `details and `isFinished` of folders items may not be populated, the items are still there in the database, but can't be parsed out, and that's why the library turns up empty, but the items are still in the database, so when adding new items, and the library tries to load the screen by pages, the stored items are making the offset work wrong, returning part of the items of the first page for the second page, resulting in duplicated items.

Now that it's clear what's happening, I can upload a fix to the AppStore, hopefully it'll be live by tomorrow, I'll post back when it's ready

**Comment by GianniCarlo** [comment] 2023-06-20 23:26
Alright, got a build on TestFlight live right now with a fix for this (link to join: https://testflight.apple.com/join/xLDneJXN), please let us know if it fixes your issue, just a heads-up, folders that may have previously disappeared due to the bug, may appear with blank details on first launch, but on subsequent app launches they'll be populated correctly

**Comment by mckayfackrell** [comment] 2023-06-21 02:48
Just did the TestFlight and opened the app. Everything worked fine and my books and folders of books appeared properly. 

Granted this all after I originally deleted the app and reloaded the books.

**Comment by GianniCarlo** [comment] 2023-06-21 04:46
Thanks @mckayfackrell , it's good to know that it keeps working when coming from a functional state of v5.0.0 👌

**Comment by GianniCarlo** [comment] 2023-06-21 21:03
I've got confirmation from other users via mail support, and it looks like it's working for those who didn't delete the app as well.

v5.0.1 is live on the AppStore, I'm closing this issue, but feel free to post back if anything comes up

**Closed by GianniCarlo** 2023-06-21 21:03 UTC
Labels: bug
