### ISSUE TITLE
Bug: Autoplay not working on playlist

### ISSUE THREAD

**Issue by lukaszmojek** [TortugaPower/BookPlayer#656] opened 2021-10-31 15:21 UTC
## Environment

 - OS Version: iOS 15.1
 - App Version: 4.2.0-11

## Description

After finishing currently playing item on the playlist, next item is not played automatically.
I have noticed the issue just today, that is 31/10/2021.

## Steps to reproduce the behavior
1. Create a playlist
2. Add some audio files to it
2. Select one of the items
3. Scroll to the end of the currently playing item
4. Next item is not played, it stays on the previous one

**Comment by n-stone** [comment] 2021-10-31 18:41
I can confirm this bug.
Same Version,
OS Version: iOS 15.1
App Version: 4.2.0-11

**Comment by Schizocarp** [comment] 2021-10-31 19:26
I can also confirm this bug.
Same version.
iPhone 13

**Comment by tundrablasen** [comment] 2021-10-31 19:32
Can confirm this bug. Not having continued playback makes the app not usable for audiobooks since they mostly consists out of hundred single files

**Comment by ricorick** [comment] 2021-10-31 19:58
Same for me no auto playback in playlist

**Comment by GianniCarlo** [comment] 2021-10-31 21:20
Thanks for reporting this guys, the fix was merged today in the PR #655, we'll submit a new version for review later today

**Comment by riotbay** [comment] 2021-11-01 12:10
Disappointed to report I’m experiencing the same issue for the past few days. I have an Iphone 11 Pro Max (IOS 15.1).
This app has been a lifeline for listening to my audiobooks all day.  It simply won’t advance to the next file which makes the app now wholly unusable- especially when driving. 😔

**Comment by Schizocarp** [comment] 2021-11-01 12:14
> Thanks for reporting this guys, the fix was merged today in the PR #655, we'll submit a new version for review later today

Thank you. Looking forward to getting back to my books.

**Comment by Alosier10** [comment] 2021-11-02 11:16
Same here. On iOS 14.7.1, BookPlayer 4.2.0 (iPhone Xr). Looking forward to a fox and thanks for your help!

**Comment by Schizocarp** [comment] 2021-11-02 11:24
> Same here. On iOS 14.7.1, BookPlayer 4.2.0 (iPhone Xr). Looking forward to a fox and thanks for your help!

![7BA2AFA3-A726-463C-91B1-C3CF43DF24DC](https://user-images.githubusercontent.com/93490699/139837603-078a4e12-99b5-4e00-950f-7e2e0ea8b118.jpeg)

**Comment by ismael-iskauskas** [comment] 2021-11-02 17:24
The Update today fixed this bug. 
Thank you all for the quick fix. 
You are the Beat

**Closed** 2021-11-02 17:46 UTC
Labels: bug
