### ISSUE TITLE
Cover picture display

### ISSUE THREAD

**Issue by meeres** [TortugaPower/BookPlayer#664] opened 2021-11-02 02:10 UTC
## Environment

 - OS Version: [e.g. 14.3]
 - App Version: [e.g. 4.2.0-11]

## Steps to reproduce the behavior
1. Add file with cover picture of a size other than a square.
2. Preview thumbnails and now playing page will display a squished version of the cover. 

Suggestions:
The squished look of the cover looks very aesthetically displeasing, and looks especially off when human faces are involved. Granted most recent audiobooks have a square cover, but there are many in my collection with different dimensions. The old version of the player displayed the cover in its original proportions, which was a good solution. Alternatively the display could crop the cover to a square or add coloured borders to maintain the square look.

**Comment by pichfl** [comment] 2021-11-02 09:20
Please do use the search function before creating a new issue. This is a duplicate of #658 and will be solved with the next update to be released in a few days.

**Closed by pichfl** 2021-11-02 09:20 UTC
Labels: bug
