### ISSUE TITLE
Autoplay not working on files imported by airdrop

### ISSUE THREAD

**Issue by flo-assling** [TortugaPower/BookPlayer#265] opened 2018-10-25 14:16 UTC
Hey,

I love that App.
What I want to do with it, is play an Audiobook, which is split into many MP3‘s - 1 per chapter.
I transferred them via Airdrop, imported into one Playlist.
I enabled „Autoplay Library“, but playback stops after every MP3 (chapter)...

**Comment by GianniCarlo** [comment] 2018-10-25 14:38
hi @flo-assling , for testing purposes, can you please try out the autoplay with the screen on? 

In the latest release we included a fix for the autoplay not working when the iPhone was locked, since the files were being imported with the default file protection which is to lock access of everything when the iPhone was locked

**Comment by flo-assling** [comment] 2018-10-25 15:31
Yes, it works while the screen is unlocked :)

Does that mean that i only have to wait for an updated App?

**Comment by GianniCarlo** [comment] 2018-10-25 15:36
Thanks for reporting this @flo-assling, it seems that the fix we included doesn't cover all the cases, we'll do some testing with the steps you provided and we'll have a fix for the next release 👌

**Comment by flo-assling** [comment] 2018-10-25 15:42
Understood. I am on a iPhone Xs Plus with iOS 12.0.1

**Comment by GianniCarlo** [comment] 2018-10-31 14:58
closed by #267

**Closed by GianniCarlo** 2018-10-31 14:58 UTC
Labels: bug

**Comment by Serendigity** [comment] 2018-11-14 05:44
I am finding this same problem as of 13Nov18 using iOS latest version 12.0.1 with iPhone Xs Plus using Airdrop to transfer files.

**Comment by pichfl** [comment] 2018-11-14 11:54
@Serendigity what version of BookPlayer is installed on your device? You can find the precise version string inside Settings.

**Comment by GianniCarlo** [comment] 2018-11-14 19:17
thanks @Serendigity 👌

**Comment by Serendigity** [comment] 2018-11-15 21:32
I have been listening to an audiobook with the latest version of the app and did not notice any problem when moving from one file to the next. BookPlayer 3.2.0-9 on iOS 12.1.  I can confirm the issue is resolved for me.

**Comment by GianniCarlo** [comment] 2018-11-15 21:33
Thanks @Serendigity for letting us know
