### ISSUE TITLE
Pause playback end of chapter not working 

### ISSUE THREAD

**Issue by Tryingtosleep** [TortugaPower/BookPlayer#885] opened 2023-03-27 03:58 UTC
## Environment

 - OS Version: iOS 16.3.1
 - App Version: 4.7.2

## Description

Sleep function bug: Playback continues to next chapter, or if on the book’s last chapter, to the next book, when selected to stop playback at the end of chapter.  Note, playback stop function works when setting custom time. 

## Steps to reproduce the behavior
1. Playing back 
2. Press moon
3. Select End of Current Chapter

**Comment by Tryingtosleep** [comment] 2023-03-28 13:45
Update. I did a longer experiment with timed stop (16m). That also failed to stop after 16m.  So it seems to not just be the end-of-chapter function that has the bug.

**Comment by rh63** [comment] 2023-04-13 19:54
Can confirm the behavior that stopping at the end of the current mp3 file does not work. This is annoying me for several months, but I cannot remember which update brought this bug. It did work before, though…

On my iPhone the timed stop does work though. I tested especially the 16 min setting 😉 – no problem.

**Comment by rh63** [comment] 2023-06-28 00:01
This annoying bug still exists in the newest version 5.0.2.

According to my observation, BookPlayer does recognize the end of the file (the "Active" marker nearby the crescent disappears), it just does not care to stop and continues playback with the next file.

I don't know if that observation helps to fix the bug, but since this function already did work in the past, I hope that the dev(s) won't have to invest too much time to make it work again.

Apart from that, BookPlayer is still indispensable on my iPhone!

**Comment by GianniCarlo** [comment] 2023-06-28 01:22
Hey @rh63 ! Thanks for following up, tbh since v5 had so many changes, I wasn't sure what of the current list of tickets were still valid. I'll add it to the list for the next patch version v5.0.3 and see if I can reproduce the behavior. Can you confirm is this happens wen playing the mp3s as volumes? Or is it when playing the mp3s as single items on a folder?

**Comment by rh63** [comment] 2023-06-28 16:08
Hi @GianniCarlo,

thanks for your quick response.

My audio books are folders full of mp3-files which are imported from my PC. The files usually have a size of 4-8 MB, a play duration of 4-12 minutes, and include a high-res cover art (1000x1000px; < 1 MB).

HTH!

Cheers!
Ralph

**Comment by mifranc** [comment] 2023-06-30 23:12
Hi, I also want to confirm I have the same issue on my phone (iPhone 7, BookPlayer 4.7.2-1, iOS 15.7.6, listening to m4b audiobooks with chapters. The End of current chapter setting doesn't stop the playback at the end of the chapter, but jumps to the next chapter and stops after a couple of seconds. (I haven't measured the other options (5min, 10min, etc), as this issue doesn't really matters to me for these, even if it would behave the same way)

**Comment by GianniCarlo** [comment] 2023-07-19 17:02
Hey everyone, I finally have a fix for this, it's currently live on a beta (link to join: https://testflight.apple.com/join/xLDneJXN) as I'd like feedback also on the shake-to-snooze functionality I put in as well (on a later version, I plan on adding a settings screen for the sleep timer to toggle both the fade-out and shake features)

Let me know how it goes @Tryingtosleep , @rh63 , @mifranc

**Comment by rh63** [comment] 2023-07-19 23:38
Hi Gianni,

unfortunately, I cannot test this beta. The app crashes reproducibly when I try to import audio files. It doesn't matter whether the files are .m4b or .mp3 (I downloaded some material from free audio book websites, e.g. <https://freeclassicaudiobooks.com>).

The beta does not only crash, it also won't start anymore after a crash. For another attempt I have to delete the app and reinstall it from within the TestFlight app.

Sorry for the bad news… 😞

**Comment by GianniCarlo** [comment] 2023-07-20 02:36
@rh63 oh no, I'll go through TestFlight crash reports and figure out what's happening there, thanks for reporting back

**Comment by GianniCarlo** [comment] 2023-07-20 04:24
@rh63 I put up a new beta which fixes the crash you were seeing, it was related to some VoiceOver translation updates for v5.0.5, and limited to a subset of the languages we support (more info on #969)

**Comment by rh63** [comment] 2023-07-20 23:55
Hi @GianniCarlo,

this new beta version really did the trick for me! 😁 Not only does the import of audio files (single or a bunch within a zip file) work flawlessly without any crashes, but BookPlayer stops playback again when reaching the end of a chapter. 🥳

Many, many thanks for your efforts!

Cheers!
Ralph

**Comment by GianniCarlo** [comment] 2023-07-23 07:10
Closing this issue, as this was included in v5.0.5 👌 (v5.0.6 currently live on the AppStore)

**Closed by GianniCarlo** 2023-07-23 07:10 UTC
Labels: bug
