### ISSUE TITLE
Bug: Ordering of files in playlist isn't following correct order

### ISSUE THREAD

**Issue by VikramTiwari** [TortugaPower/BookPlayer#508] opened 2020-10-29 17:52 UTC
# 🌎 Environment

 - OS Version: iOS 14.1
 - Version/Release: 3.10.1-1

# 💬 Description

When I have more than 100 files in a playlist, I often see that the order of files gets mangled because of the naming scheme.
# 🦶 Reproduction Steps
If I name the files as 001 to 150. The files in the playlist will be 138, 139, 014, 140, 141, 142. Essentially the files from 120-129 are played between 012 and 013, files from 130-139 are played between 013 and 014 and so on

Steps to reproduce the behavior, provide an example of the command line issued:
1. Have more than 150 files following the naming scheme of 001, 002 ... onwards
2. Import files in a playlist
3. You will see the order being incorrect

# 🤔 Expected Results
The order should be 011, 012, 013, 014 and so on

**Comment by VikramTiwari** [comment] 2020-10-29 22:13
Hey @GianniCarlo I don't have any experience with swift but I can take a stab at this.

Would this be a good place to start? https://github.com/TortugaPower/BookPlayer/blob/bcf7d49e592efbd0d6bbf633fcaef7185b00fbd4/BookPlayer/Library/DataManagement/DataManager+CoreData.swift#L30 Assuringly, you would want to sort the files before they get added in existing book/playlist.

Also, I am not sure how it works right now. Based on this code I would have assumed the order to be totally random. Does swift guarantee the files order in some form? If that's the case then I will look more into that.

**Comment by NCrusher74** [comment] 2020-12-16 02:41
I'm... not really certain how the process should go to submit a PR fixing an issue, as I've never done it before, and I appear to be missing some dependencies when I try to build. So instead, I'll just suggest a solution here.

First, add this convenience extension:

```swift
extension URL {
    /// Isolates and returns a filename string from a `URL`
    var fileName: String {
        get {
            let filename = self.deletingPathExtension().lastPathComponent
            return filename
        }
    }
}
```

Then change the line you flagged (Line 30 of DataManager+CoreData.swift) as follows:

```swift
        for file in files.sorted(by: {$0.originalUrl.fileName < $1.originalUrl.fileName}) {
```

That would sort the files based on the file name of their original URL. It might actually be better, however, to catch this before the file is turned into a `FileItem`, but I'm not sure where that happens. This might at least be a start?

**Comment by GianniCarlo** [comment] 2021-08-17 23:36
This should already be fixed in v4.0.0 released today, feel free to reopen in case it's still happening

**Comment by s00d** [comment] 2021-09-03 19:54
![IMG_002139](https://user-images.githubusercontent.com/2684895/132059065-891560f4-1280-4035-a2d5-b15ed60d4a99.PNG)
<img width="204" alt="Screenshot 2021-09-04 at 00 52 28" src="https://user-images.githubusercontent.com/2684895/132059078-0d118383-c6bd-4764-a58e-625a52c9418d.png">
How does this happen? version 4.1.0 
all my mp3 books in random order

**Comment by EverlastEngineering** [comment] 2021-12-15 13:13
I'm experiencing this tool. Can debug on request if necessary.

**Comment by r0bj** [comment] 2021-12-16 04:23
I can confirm issue with wrong order, version 4.3.0

**Comment by GianniCarlo** [comment] 2021-12-26 18:10
@EverlastEngineering @r0bj , I've been trying to reproduce this issue simulating the list of the screenshot (001.mp3, 002.mp3 ...), and airdropping them, but when they are finished importing, they are sorted correctly. Can someone give me another example of lists to try out?

**Comment by EverlastEngineering** [comment] 2021-12-27 16:37
This is the sequence that failed to auto detect the order. I found the manual ordering button and was able to select one that seems to have worked, but out of the box, this didn't work:

![image](https://user-images.githubusercontent.com/2895375/147490765-0a9f3279-efbd-402e-b3bf-3bf19908eca1.png)

**Comment by EverlastEngineering** [comment] 2021-12-27 16:38
Also due to the length of the filename and char limit in the app when displaying the files, I couldn't see which files were in which order, as that may have helped.

**Comment by GianniCarlo** [comment] 2021-12-28 04:03
Alright, it turns out we were just sorting the incoming files in a shallow way, so if one of the files/urls was a folder, the contents weren't being sorted, there's a PR addressing this issue and it will be included in the next release

**Comment by GianniCarlo** [comment] 2021-12-30 01:27
Alright everyone, the next beta is live and should solve this issue 😁. If you'd like to join, here's the link: https://testflight.apple.com/join/FLv3zLyN otherwise we'll submit this version for AppStore review around Jan 6 🙌🏻

**Closed** 2022-04-17 23:46 UTC
Labels: bug, help wanted
