### ISSUE TITLE
iPad

### ISSUE THREAD

**Issue by Mrtz11** [TortugaPower/BookPlayer#516] opened 2020-11-17 22:44 UTC
Please adapt the app for the iPad. Otherwise it is only displayed in very small or enlarged and blurred form. It's really not nice. Otherwise the app is very good, thank you very much

**Comment by pichfl** [comment] 2020-11-17 23:03
Duplicate of #230 
Duplicate of #517

**Closed by pichfl** 2020-11-17 23:03 UTC
Labels: duplicate
