### ISSUE TITLE
Importing not working with 4.2.2

### ISSUE THREAD

**Issue by BayRider27** [TortugaPower/BookPlayer#684] opened 2021-11-09 21:12 UTC
## Environment

 - OS Version: 14.8.1
 - App Version: 4.2.2

## Description

4.1.1 worked beautifully but with the first 4.2 version I started having problems importing files to BookPlayer. I also found that my multiple part play lists stopped playing at the end of a part. I had to select the next part in the play list manually. 

I usually import multiple m4b files to add to a playlist via Airdrop. With 4.2 I had to I had to import each file individually. With 4.2.2 I cannot import any file via Airdrop. I then tried to import from Dropbox and this did not work either. Files show up in the Dropbox app but BookPlayer will not import them, only spin on the Downloading graphic. 

## Steps to reproduce the behavior
1. Try to AirDrop a file to phone. 
2. I see the Destination pop up on phone, select BookPlayer. 
3. Nothing happens. No new m4b file appears in BookPlayer.

**Comment by dfdy** [comment] 2021-11-16 16:31
I have the same problem.

**Comment by BayRider27** [comment] 2021-11-17 02:06
> I have the same problem. I have tried both airdrop and importing from icloud.
> 
> * OS Version: 15.1
> * App Version: 4.2.2

Thanks for the report. I was just thinking that moving to iOS 15 might fix the import issue. You’ve saved me that effort, much appreciated. 

I can update my feedback: 4.2.2 does move smoothly between parts in a playlist, which the previous version did not. So that’s one improvement. Still can’t import though, just tried via a different computer.

**Comment by GianniCarlo** [comment] 2021-11-17 15:47
I figured out what the issue is (or at least one of the issues), if the app isn't already loaded up in memory, and it's started by airdropping, the app boots up, but misses the airdrop event. I'll figure out a fix for this for the next version 👍 

In the meantime, test by first opening the app before airdropping the files

**Comment by BayRider27** [comment] 2021-11-17 17:44
Thanks for reply and considering our situation. In the past I’ve only been able to airdrop multiple book parts if the app was not already open so that has become my habit. When I get off work I will try with the app already in memory. Thanks again.

**Comment by dfdy** [comment] 2021-11-17 19:45
In my case the app was already open when I tried to AirDrop and also when I tried to import from iCloud. 

In a very annoying twist, I tried again today (AirDrop) and it worked perfectly the first time. 

Intermittent bugs - everyone's favourite kind. ¯\_(ツ)_/¯

**Comment by BayRider27** [comment] 2021-11-18 05:28
Just airdropped a 3-part book the first try with the app already open, yay! So glad to have a new book available. Not sure how to help sort out the intermittent nature of the situation. Lmk if I can test something.

**Comment by GianniCarlo** [comment] 2021-11-18 14:00
@BayRider27 I found two other issues while fixing the one I mentioned, the PR #691 addresses all the issues I found, I'll see if I can submit a new version with this fix this week, and hopefully we can have it live by the weekend

**Comment by GianniCarlo** [comment] 2021-11-22 03:57
@dfdy @BayRider27 version 4.3.0 was released earlier today, can you update and test importing?

**Comment by BayRider27** [comment] 2021-11-22 06:37
Just tried several situations with two different .m4b files. With app not loaded into memory, both failed to add to Bookplayer library. 

With app loaded into memory but not in foreground (some other app showing on phone screen), both files failed to add to Bookplayer library.

With app open and in foreground, both files were added to library successfully. 

So this seems a big improvement, just need to open the app and make sure it is active when adding books. I will try to add some more files just to test tomorrow, but wanted to give you a bit of feedback asap. Thanks!

**Comment by GianniCarlo** [comment] 2021-11-22 11:01
Thanks @BayRider27 ! Damn I really thought I covered all the cases. I'm refactoring part of the codebase that handles the database and adding unit tests, I'll circle back to this after that

**Comment by BayRider27** [comment] 2021-11-23 16:09
Update: just tried several sets of .m4b files in various app states with Version 4.3.0. Each attempt to import worked perfectly. I have no explanation for the problems related in my previous post - maybe the app hadn't updated to 4.3 correctly? I did restart my phone for an unrelated situation, so perhaps that sorted something out with 4.3 correctly replacing the previous version. Sorry but I just don't know what happened. The point is that everything is working now. 

I noticed something new - there is a very quick notification of Airdrop activity before the screen asking where to send the Airdropped files. I don't recall seeing this before with previous imports to Bookplayer. probably meaningless but just thought I'd mention it. The new (to me) notification happens so quickly that I had to do a screen recording that I could then pause on playback to see what it said. 

So thanks again very much for helping to fix this importing issue. I do have a couple of other imperfections I could bring up, given that I use the app for hours every day. Should I list those here or start a new Github post or email directly?

Also, thinking about how much use I get out of Bookplayer, I just hit the Tip Jar again. Thanks again for this great app!!

**Comment by BayRider27** [comment] 2021-11-23 16:16
Forgot to mention - another change I really appreciate is that when importing a sequence of files, the suggested new playlist title ignores the 01, 02, 03... prefixes. This is GREAT!!! Saves me having to move the cursor to the front and delete the 01. Thanks for this!

**Comment by GianniCarlo** [comment] 2021-11-24 11:54
Thanks @BayRider27 for your continued support :D 🎉! regarding other issues, feel free to open new tickets in Github for those 👍

**Comment by GianniCarlo** [comment] 2021-11-24 11:55
I'll close this issue, but feel free anyone to continue the conversation in case something comes up

**Closed by GianniCarlo** 2021-11-24 11:55 UTC
Labels: bug
