### ISSUE TITLE
Loosing links to stored bookes

### ISSUE THREAD

**Issue by xmeir** [TortugaPower/BookPlayer#790] opened 2022-05-17 13:14 UTC
## Environment

 - iOS: 15.4.1
 - Phone: IPhone 11 (MWM02CN/A)
 - App Version: 4.5.0-4

## Steps to reproduce the behavior
1. Book imported as multiple mp3s through the app.
2. During import combined into volume by the app and named using Czech characters (Maigretův první případ).
3. In Settings -> Storage management files show warnings for all imported files (yellow warning sign icon). The error reads "The book item is missing, if the corresponding item cannot be found, a new one will be created.".
4. When fixing the files, the app reports duplicates. After finishing fix, book is still visible in Library, but can't be played anymore (nothing happens when clicking play button or app reports missing URL or app crashes). Seems all files were removed (storage shows only few bytes used space).

**Comment by GianniCarlo** [comment] 2022-05-18 02:13
Thanks for reporting the issue @xmeir ! there seems to be an issue with the storage management screen, in the meantime, you should be able to play your books after importing and combining them into a volume (please let me know if this is not the case, I tested locally using the same name you mentioned 👍 )

**Comment by xmeir** [comment] 2022-05-18 08:11
Hello GianniCarlo, indeed books play fine if I don’t fix the error in the storage management. I also tested conversion to M4B file prior to import and it works with no glitch so far (tested 3 books, all using CZ characters in name of book and chapters).

**Comment by GianniCarlo** [comment] 2022-05-19 20:38
So the problem is that when reading the file url, the special characters get decoded visually right, but underneath it's fundamentally different, see the following example for `ů`:

<img width="648" alt="Screen Shot 2022-05-19 at 13 15 03" src="https://user-images.githubusercontent.com/14112819/169373267-5009d3ff-f5e6-4f82-9bd7-fc46a70e26c1.png">

both should print `\u{016F}`, and I'm guessing that it's because the file url is percent encoded as `u%CC%8A`, and when decoded it looks visually the same, but underneath it's different. This is why the storage screen fails to find the corresponding item in the DB starting from a file url (the search predicate looks visually ok when printing it out in the console), but when doing playback, there's no problem because we start with the object in the DB.  Not sure yet how to properly approach this though, I'll test some solutions, but I'm open to suggestions

**Comment by GianniCarlo** [comment] 2022-05-21 14:11
The fix will be included in the next release 👍

**Closed by GianniCarlo** 2022-05-21 14:11 UTC
Labels: bug
