### ISSUE TITLE
Bug: Storage management menu fails to detect files from failed imports

### ISSUE THREAD

**Issue by lilgrassin** [TortugaPower/BookPlayer#707] opened 2021-12-09 02:15 UTC
## Environment

 - OS Version: 14.8.1
 - App Version: 4.3.0-1

## Description

I just discovered that files that fail to import via AirDrop due to #684 stick around in the app's storage, but are not detected by BookPlayer's storage management settings. This means there are several GBs worth of duplicate files that are hard to clean up because I can't tell which one BookPlayer is using (in my case because of truncated filenames). Here are screenshots from BookPlayer's storage menu vs iOS's storage menu showing the difference:

<p float="left">
<img src="https://user-images.githubusercontent.com/11161002/145320106-81a2879b-343e-4326-aefb-a64c42b2d873.PNG" width="250px"> 
<img src="https://user-images.githubusercontent.com/11161002/145320125-e789d3a5-0fcb-48a4-87e7-add9bf9e066c.PNG" width="250px"> 
<img src="https://user-images.githubusercontent.com/11161002/145320145-f6790dd9-3662-45af-9800-2f88642ff45a.PNG" width="250px">
</p>

## Steps to reproduce the behavior
1. Follow #684 to reproduce failed import
2. Confirm file does NOT appear in BookPlayer's storage management. Additionally the amount of storage in use is not updated.
3. Confirm file DOES appear in iOS's storage management for BookPlayer, as well as the correct amount of storage used.

**Comment by GianniCarlo** [comment] 2021-12-09 10:45
Thanks for reporting this @lilgrassin !, to reproduce the import issue, after airdropping and the import screen being shown, force-close the app, and the files will get stuck in the Inbox folder

For more context, inside the Documents folder in the app, there are only two folders:
1. the Processed folder, which is the root for the library, and the folder that is considered for the storage management
2. the Inbox folder, which is created by the system when something is airdropped. Since this folder is created by the system, we thought it would get eventually deleted by it, like a tmp folder, but it turns out it's not deleted.

#709 adds a check to show the import screen to the user again with the Inbox folder contents. The storage management screen should only consider the library folder, given that anything outside of it, are books that should have been or will be imported.

If you'd like to get rid of them before the new version is out, you can plug your phone into your computer, go to the file sharing section, select BookPlayer, and delete the Inbox folder

![Screen Shot 2021-12-09 at 5 45 19 AM](https://user-images.githubusercontent.com/14112819/145382239-175a11fd-f797-493f-80a4-c43aa4967e46.png)

**Comment by GianniCarlo** [comment] 2021-12-17 21:40
with v4.4.0 now available in the appstore, the files shouldn't be able to hide in the Inbox folder for long anymore. I'm closing this issue, but if something related comes up, please feel free to continue the discussion

**Closed by GianniCarlo** 2021-12-17 21:40 UTC
Labels: bug
