### ISSUE TITLE
Bug: ... app crashes when importing files

### ISSUE THREAD

**Issue by angelcie** [TortugaPower/BookPlayer#702] opened 2021-12-01 14:15 UTC
## Environment

 - OS Version: 

> [14.8.1]

 - App Version: [4.3]

## Steps to reproduce the behavior
1. open bookplayer app
2. open file app
3. click file to import to bookplayer app
4. click done
5. app  #crashes[]
6. (https://youtube.com/shorts/zz9BjZcsR8g?feature=share)

**Comment by XiaoHippo** [comment] 2021-12-04 17:37
Files -> Share crashes the app, definitely a regression. Import Files seems to have better success rate.

**Comment by GianniCarlo** [comment] 2021-12-07 03:13
I managed to reproduce this issue, it looks like it's related to the Operation queue we're using. When adding to the queue, for some reason the operation may have already started

**Comment by GianniCarlo** [comment] 2021-12-07 03:30
We added a missing check to `isCancelled` when starting an operation, let's see if that fixes this issue in the next release

**Comment by GianniCarlo** [comment] 2021-12-17 21:40
@XiaoHippo v4.4.0 is out now in the AppStore, please let us know if you are still experiencing this issue

**Comment by XiaoHippo** [comment] 2021-12-18 03:33
Unfortunately it doesn't seem to fix it. I have BookPlayer open, then:
1. Go to Files, navigate to my server
2. Long-press on an audiobook file and tap Share
3. Tap BookPlayer
4. The Import page in BookPlayer shows
5. Tap Done, BookPlayer crashes

If I start in BookPlayer's library UI, tap Add, then Import Files, then navigate to the server, tap the audiobook file, it works.

Please let me know if I can help send over some diagnostic files.

**Comment by GianniCarlo** [comment] 2021-12-18 16:25
Ooooooh ok, I've seen this before, I thought it was only a thing happening on the iPad when long-pressing the app, it pops up recent files from the Files app and lets you drag them on top of the app. I'm guessing it's the same operation underneath (from Files to BookPlayer), for some reason in that operation when trying to copy the file from the source path, it's crashing because the file is not there

I'll do some tests, and see where the source file actually is

**Comment by XiaoHippo** [comment] 2021-12-18 16:47
Thanks. Just FYI the file I chose was not from the Recent folder, and this has just started to happen in the past few weeks right around when this issue was created.

**Comment by XiaoHippo** [comment] 2021-12-22 02:43
Just tried 4.4.1, still crashes. And I can repro this with these steps:
1. Save a .m4b file to Files, right under "On My iPhone"
2. Long-press on it and tap Share
3. Tap BookPlayer
4. The Import page of BookPlayer appears
5. Tap Done, BookPlayer crashes

On console, I can see the following messages before it crashes:
`12 duplicate reports for Sandbox: BookPlayer(29662) deny(1) file-read-metadata /private/var/mobile/Containers/Shared/AppGroup/4D245BF5-7F92-4DA5-8902-DAB7E668831E/File Provider Storage/Random Test - 1.m4b`
`Sandbox: BookPlayer(29662) deny(1) file-write-unlink /private/var/mobile/Containers/Shared/AppGroup/4D245BF5-7F92-4DA5-8902-DAB7E668831E/File Provider Storage/Random Test - 1.m4b`

**Comment by GianniCarlo** [comment] 2021-12-28 04:05
It turns out that when we enabled to open documents in place for the app, giving access to the internal library files from within the Files app, the files imported when starting from the Files app, have a new security scope that we have to resolve before accessing the file and making a copy. #728 addresses this issue and will be included in the next release

**Comment by GianniCarlo** [comment] 2021-12-30 01:23
@XiaoHippo this issue should be resolved in the latest beta. If you'd like to join, here's the link: https://testflight.apple.com/join/FLv3zLyN otherwise we'll submit this version for AppStore review around Jan 6 👌

**Comment by GianniCarlo** [comment] 2022-02-03 12:59
closing this issue, as it should already be resolved, please feel free to continue the discussion if this is still happening

**Closed by GianniCarlo** 2022-02-03 12:59 UTC
Labels: bug
