### ISSUE TITLE
Bug: Unable to import books via Airdrop / Open in BookPlayer

### ISSUE THREAD

**Issue by sharimorehead** [TortugaPower/BookPlayer#929] opened 2023-06-22 22:55 UTC
## Environment

 - OS Version: 16.5.1
 - App Version: 5.0.1
 - Device: iPhone 12 Pro Max 256gb w/100gb free space

## Description
I have tried multiple MP3 and M4B books using AirDrop -> BookPlayer and they never appear. Even tried to import them from files, they also do not appear. This worked fine about a week or so ago, but in the past 3-4 days, I'm unable to Airdrop and open any books in BookPlayer.

## Steps to reproduce the behavior
1. AirDrop an mp3 or m4b to iPhone
2. Tap "Open in BookPlayer"
3. It does not appear in the Library list at all

**Comment by GianniCarlo** [comment] 2023-06-23 04:19
@sharimorehead if you force quit the app, and retry airdrop, does it work? I remember in v4.x.x we had an issue where the listener thought that the app was already showing the import screen, so that could be something I need to look at. Also, what was the active screen when opening BookPlayer via the Airdrop prompt? just to have the exact scenario

**Comment by ml-dev** [comment] 2023-06-23 16:54
I am having this same issue. I have force quit the app and tried three different ways to import an audio file. 
1. Import file inside of BookPlayer.
2. Download from URL inside of BookPlayer.
3. iOS share option to BookPlayer from Files app.

All three ways resulted in the file not appearing in the library list or in the Processed folder in the FIles app.
BookPlayer 5.0.1-2 - iOS 16.5.1
Thanks for a great application!

**Comment by GianniCarlo** [comment] 2023-06-23 17:03
@ml-dev the import screen is never shown right? could you share one or two of the files just in case?

**Comment by ml-dev** [comment] 2023-06-23 17:13
@GianniCarlo, the Import screen is opening.  Here the steps to reproduce:
1. Open BookPlayer.
2. Open Library list.
3. Scroll down and tap _Add_.
4. Tap _Import files_.
5. Navigate to folder and tap file.
6. Tap _Open_ in top right.
7. The Library list is now open but the imported file is not in the list. I also checked the Files app and I do not see the file listed in the Processed folder.

**Comment by sharimorehead** [comment] 2023-06-23 22:53
For the AirDrop issue:
1. Force close BookPlayer
2. Sitting on home screen
3. AirDrop book from Mac to iPhone
4. From the iPhone AirDrop menu, select BookPlayer
5. BookPlayer opens
6. The file is not in BookPlayer

**Comment by GianniCarlo** [comment] 2023-06-24 04:03
I'm still trying to reproduce this issue, there's one point after tapping 'Open', that the import operation will try to automatically relink the files to the digital items (if there were any items orphaned without their audiobook file), if it's successful in relinking, that particular file is discarded from the set list to import.

@ml-dev @sharimorehead , Is there any alert that is presented after the import screen is dismissed?  like the one in this screenshot?

![IMG_67E448E6804A-1](https://github.com/TortugaPower/BookPlayer/assets/14112819/ee4602e7-cf5e-4a8c-8f59-b10ebcdaa650)

I'm updating my phone to iOS 16.5.1 just in case too, and see if it happens to me there

**Comment by ml-dev** [comment] 2023-06-24 15:05
@GianniCarlo I do not see that alert screen in your screenshot. After the import screen is dismissed the library list is displayed.

**Comment by GianniCarlo** [comment] 2023-06-25 16:53
As I couldn't reproduce the issue, I'm adding a way to debug the import process in #936 via a log file that you can access through the `Processed` folder, the file will be named `debug_log_file.txt`, with that in hand, it'll be easier to figure out what's happening. I've submitted the build for review to TestFlight, and will post back when it's available

**Comment by GianniCarlo** [comment] 2023-06-26 14:18
it didn't happen with the debugger attached, but after testing different scenarios without running the project, I was able to reproduce the issue, it was because the file observers were registered and triggering the import screen before the entire screen hierarchy was finished presenting (the tab bar with the three tabs), and this was failing silently, so it thought it had already presented the import screen, so whenever there were new items, it wouldn't try to show the screen again, as that screen handles updating the item list (airdrop items come in events of one file, even if the drop was for 10 files at once). The previous beta hasn't been approved yet, but once that's through, I can upload new builds without the wait time on TestFlight

**Comment by ml-dev** [comment] 2023-06-26 15:13
Thanks for tracking down this issue!  I will test again when a new release is available.

**Comment by GianniCarlo** [comment] 2023-06-26 15:48
Tesflight build is live 🙌 (link to join: https://testflight.apple.com/join/xLDneJXN) please let me know if this works

**Comment by ml-dev** [comment] 2023-06-26 16:02
Importing is working with the new build!  I had the same experience of the failed import files showing up for import.

**Comment by GianniCarlo** [comment] 2023-06-28 01:02
v5.0.2 is out! I'm closing this issue but feel free to comment if this happens again

**Closed** 2023-06-28 01:02 UTC
Labels: bug
