### ISSUE TITLE
Bug: Widget does not work

### ISSUE THREAD

**Issue by Chrischmi** [TortugaPower/BookPlayer#648] opened 2021-10-12 00:42 UTC
## Environment

 - OS Version: 14.*, 15.*
 - App Version: 14.1.1.1

## Description

Widget is a a white box w/o any content.

## Steps to reproduce the behavior
1. Add widget to homescreen
2. see white box

![7957B33E-0C59-4876-AFEB-3E239A5BCD5B](https://user-images.githubusercontent.com/6383221/136871552-98c7b44d-849a-4b8e-8d6b-71b8812586b5.jpeg)

**Comment by GianniCarlo** [comment] 2021-10-12 04:50
Is that the recent books widget? or the time played widget?, can you try on the latest version? link to beta: https://testflight.apple.com/join/FLv3zLyN If it's the recent books widget, there's a memory limit issue, we need to change how we handle the artwork data which is the root cause for this issue

**Comment by Chrischmi** [comment] 2021-10-30 21:39
Recent Books, yes.

**Comment by Chrischmi** [comment] 2021-11-07 19:32
Seems to be fixed. I am just wondering, why two chapters of one book (folder) appear as two books in the widget.

**Comment by GianniCarlo** [comment] 2021-11-14 23:18
@Chrischmi yes unfortunately that will happen for mp3 books until we get the bound books feature done. For more details, we moved away from having the database objects directly loaded on memory due to unexpected errors/behaviour when the library is too big.

I'm closing this issue as this would be resolved with #389

**Closed by GianniCarlo** 2021-11-14 23:18 UTC
Labels: bug
