### ISSUE TITLE
Latest Update Stopped App From Working!

### ISSUE THREAD

**Issue by appsteve** [TortugaPower/BookPlayer#918] opened 2023-06-18 23:13 UTC
## Environment

 - OS Version: [e.g. 13.5.1]
 - App Version: [e.g. 3.9.0-1]

## Description

The latest update has stopped the app from opening! It is showing following error when trying to open the app: “Multiple validation errors occurred.” I even deleted the app, restarted my iPhone, and installed it again, but the app still gives the same error and craps out. I may also have lost all my data! Please fix and fully test the app before releasing a new update! Thanks

## Steps to reproduce the behavior
1. Restarted iPhone
2. Reinstalled app
3. Opening app gives following error and app goes no further (craps out). I’ve been using the app daily for a few years now, so this is really sad to see. Error: “Multiple validation errors occurred.”

**Comment by appsteve** [comment] 2023-06-18 23:15
Forgot to add versions:

iOS: 16.5
App version: 5.0.0 (latest as of June 18, 2023)

**Comment by GianniCarlo** [comment] 2023-06-19 01:54
we're looking into it, thanks for the report

**Comment by nauni77** [comment] 2023-06-19 09:48
I have the same problem. Even reboot or reinstall didn't help.

iOS: 16.5
App version: 5.0.0 (latest as of June 18, 2023)

Just for information: The device is a apple iPhone 12 Pro.

Thanks for your help!

Oli

**Comment by karb0f0s** [comment] 2023-06-19 14:20
Also have this issue. Is there a way to gather log/trace to investigate?

**Comment by GianniCarlo** [comment] 2023-06-19 14:59
it looks like a CoreData issue when trying to perform migrations from the previous data model to the new one, I've been trying to replicate but with no luck

(screenshot of core data errors enum)
<img width="988" alt="Screenshot 2023-06-19 at 09 29 54" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/d2f32eae-a8b3-43e7-943b-f205f4ce593c">

Unfortunately as it is not crashing, Sentry is not reporting this case, I'll add logs with the [OS logger](https://developer.apple.com/documentation/os/logger), so they are visible with the Console app on MacOS for connected devices to help debug this in future cases. In the meantime, I'm adding this to the list of unrecoverable states we have, so the CoreData stack is reloaded and the app is at least accessible again (progress will be lost :/)

**Comment by nauni77** [comment] 2023-06-19 15:50
Hello, but why should this caused by a data mirgration process? The same error happens if I delete the complete app and install it from AppStore again. In this case IMHO there should be no data to migrate ... I'm wrong?

**Comment by GianniCarlo** [comment] 2023-06-19 18:12
@nauni77 that's a good point 🤔, it shouldn't have any issues on a clean install, can someone post a screen recording of the app launching and the alert? it's on the initial screen and stays there right? cc  @karb0f0s @appsteve 

I'll test by creating a new schema version, data model v9 went through a lot of changes before v5 was released, so probably something is not working alright under the hood there

**Comment by appsteve** [comment] 2023-06-19 20:53
The message disappears and then the app just freezes.

**Comment by nauni77** [comment] 2023-06-19 21:40
Hello, this is a complete reinstall on an iPhone that never had the application installed before. The first image shows the error message and the second image shows the display after pressing the "ok" button.
![IMG_0523](https://github.com/TortugaPower/BookPlayer/assets/39400842/b8e967d7-b34f-47b5-afaa-3334136788ae)
![IMG_0524](https://github.com/TortugaPower/BookPlayer/assets/39400842/3cff8eb4-7508-4420-bcbb-51931e73a340)

**Comment by GianniCarlo** [comment] 2023-06-19 23:35
I've submitted a build to TestFlight to test my solution, hopefully later today it'll be approved for testing. I'll post back with a link to join the test and see if it works

<img width="446" alt="Screenshot 2023-06-19 at 18 34 20" src="https://github.com/TortugaPower/BookPlayer/assets/14112819/a3ab370d-a388-4f6a-9a14-a2881108db68">

**Comment by GianniCarlo** [comment] 2023-06-20 23:28
The build is live on TestFlight (link to join: https://testflight.apple.com/join/xLDneJXN), this should in any case force the database to load, and not let the app stay in the loading screen, please let us know if it works

**Comment by appsteve** [comment] 2023-06-21 00:27
Managed to get into the app, but lost all my data and files. Also, app is now asking for a subscription and it wasn’t before!

**Comment by GianniCarlo** [comment] 2023-06-21 00:34
@appsteve yes when you deleted the app, all the imported files are deleted as well with the app contents. For those who haven't deleted the app yet, the files should show up, but the progress most likely will be lost. We're moving away from CoreData to Realm for the local database solution, as there's always something that happens with the big migrations (also Apple this year just came up with a replacement framework but it's for iOS 17+)

Regarding the subscription, this is only if you're interested in cloud sync, as we had to implement our own solution and have to cover the server costs. The rest of the app is free as always

**Comment by GianniCarlo** [comment] 2023-06-21 21:04
v5.0.1 is live on the AppStore, I'm closing this issue, but feel free to post back if anything comes up

**Closed by GianniCarlo** 2023-06-21 21:04 UTC
Labels: bug

**Comment by nauni77** [comment] 2023-06-21 21:31
@GianniCarlo : Thanks for your help.

**Comment by appsteve** [comment] 2023-06-21 22:08
I don’t see the update on the Canadian Apple AppStore yet.

**Comment by GianniCarlo** [comment] 2023-06-21 22:36
@appsteve it should show up shortly 👍, I'll wait more time next time before announcing a new version, as it takes some time for the new version to propagate throughout the AppStore

**Comment by appsteve** [comment] 2023-06-21 22:58
Thanks 🙏
