### ISSUE TITLE
Bug: Newly copied audiobooks not recognized by the app

### ISSUE THREAD

**Issue by Karthik9479** [TortugaPower/BookPlayer#1074] opened 2024-01-13 07:13 UTC
## Environment

 - OS Version: 17.2.1
 - App Version: 5.1.21-28

## Description

i upgraded from iPhone 11 pro to 15 pro Max. I did a backup and restore on my new Phone. After this, whenever I try to copy an audiobook, the files are not recognized by the app. 

I did install the TestFlight version and the result is still the same.

Sometimes after the restart of phone, the app identifies the copied books. That too some time. I can see the book on folder above the Processesed folder.

I had reported this email too. The dev was kind enough to look into this and acknowledged that the issue and provided another Test flight version but the same happened with newer version .So I tried reverting to Appstore version and the issue still persists.

Any other means to copy books to the app?

Thank you

**Comment by GianniCarlo** [comment] 2024-01-13 17:22
Hi @Karthik9479 ! sorry I must have missed the support email. Regarding other ways to import the books, there's [a wiki](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-import-audiobooks-into-bookplayer) going over the options, I'm happy to clarify more on any of the items. 

I wasn't able to reproduce this issue on my 13 mini, but I had a chance to test it on a 15 pro, and there I was able to reproduce the same issue I thought I had fixed on [this commit](https://github.com/TortugaPower/BookPlayer/pull/1038/commits/cceb185d6281bc228fbeff0b4737fc63544ddcf7). I'll have a chance later today to spend some more time with the 15 pro, so I can debug what's the issue. Looks like it's time to upgrade my phone 😬

**Comment by hdo** [comment] 2024-01-14 10:33
Maybe it's a good idea to add a 'Force reload/refresh'  button to the settings page? With this one can re-import/re-load the whole library. I also noticed a missing "file change" notification on my testing (iPhone 8).

**Comment by Karthik9479** [comment] 2024-01-14 13:19
> Hi @Karthik9479 ! sorry I must have missed the support email. Regarding other ways to import the books, there's [a wiki](https://github.com/TortugaPower/BookPlayer/wiki/FAQ#how-to-import-audiobooks-into-bookplayer) going over the options, I'm happy to clarify more on any of the items.
> 
> I wasn't able to reproduce this issue on my 13 mini, but I had a chance to test it on a 15 pro, and there I was able to reproduce the same issue I thought I had fixed on [this commit](https://github.com/TortugaPower/BookPlayer/pull/1038/commits/cceb185d6281bc228fbeff0b4737fc63544ddcf7). I'll have a chance later today to spend some more time with the 15 pro, so I can debug what's the issue. Looks like it's time to upgrade my phone 😬

No worries and Thank you much for the great work you are doing

I did the following today
- UnInstalled the app.
- Reinstalled the app from appstore
- Tried copying the books again
- Same result.
Then later I did find a way to use the "Import" functionality to import from the Folder 

So I am able to use it now.

**Comment by GianniCarlo** [comment] 2024-02-02 20:24
@Karthik9479 @hdo v5.2.0 is out now, and it includes a pull down to refresh to force the import scan, please let me know if you have any problems

**Closed by GianniCarlo** 2024-02-02 20:24 UTC
Labels: bug
