### ISSUE TITLE
App shuts down repeatedly

### ISSUE THREAD

**Issue by grzkv** [TortugaPower/BookPlayer#455] opened 2020-05-02 14:50 UTC
After todays update app halts all the time, roughly every 20 minutes of listening. 

BookPlayer 3.8.2-1
iPhone 7 - iOS 13.3.1

**Comment by GianniCarlo** [comment] 2020-05-02 22:51
Hi @grzkv , just to be clear, the app is crashing on background while you're listening?

**Comment by grzkv** [comment] 2020-05-03 10:36
Hi @GianniCarlo! 

I am observing two scenarios:
1. App crashes in the background
2. App crashes when I scroll across a long playlist. When scrolling, it first becomes laggy, and then the crashes.

**Comment by GianniCarlo** [comment] 2020-05-04 02:23
I'm seeing crashes when the OS notifies the app that an interruption is over, and it should resume the audio:

<img width="682" alt="Screen Shot 2020-05-03 at 21 20 17" src="https://user-images.githubusercontent.com/14112819/80932168-e4f95880-8d83-11ea-9157-cfc54c96d53b.png">

So this crash is happening because when BookPlayer tries activate the audio session and get a hold of it so it can start reproducing audio again, it failes

<img width="427" alt="Screen Shot 2020-05-03 at 21 21 09" src="https://user-images.githubusercontent.com/14112819/80932181-035f5400-8d84-11ea-970f-138d965f1327.png">

We've defaulted to always crash the app when this happens, because we've found out that once the app tries and fails to activate the audio session, it will no longer be able to activate it in future retries, until it is closed/killed manually and relaunched.

Not sure if this could be your case though, while you were listening, did a call come in? was siri activated? or any other possible interruption to the playback might have occurred?

**Comment by grzkv** [comment] 2020-05-06 11:42
> Not sure if this could be your case though, while you were listening, did a call come in? was siri activated? or any other possible interruption to the playback might have occurred?

There were no interruptions to my best knowledge.

If there were interruptions, I would not consider this a bug. I guess, it is expected that playback stops after an interrupt. 

> App crashes when I scroll across a long playlist. When scrolling, it first becomes laggy, and then the crashes.

This scenario happens more frequently than the other one.

**Comment by patjolata** [comment] 2020-05-26 20:28
@GianniCarlo Is this also the reason why I see the app crashing always after I opened it and enter the chapters? Was just wondering or should I open a new issue?

**Comment by GianniCarlo** [comment] 2020-05-27 04:19
hi @patjolata , mmmmm depends, if by chapters you're referring to a playlist of mp3s, then it could be related to the second point of @grzkv 
> 2. App crashes when I scroll across a long playlist. When scrolling, it first becomes laggy, and then the crashes.

But if you mean chapters from a single book that are accessed via the player view, then yeah, it's unrelated to this issue

**Comment by patjolata** [comment] 2020-05-27 06:31
@GianniCarlo Oh, no, than it is unrelated. The crash happens when I'm in playback mode and git the chapter of a single audio book. Can you split this issue or shall I open a new one?

**Comment by grzkv** [comment] 2020-05-31 15:05
> @GianniCarlo Is this also the reason why I see the app crashing always after I opened it and enter the chapters? Was just wondering or should I open a new issue?

This looks like a separate issue to me.

**Comment by grzkv** [comment] 2020-05-31 15:08
@GianniCarlo Just to keep you informed, I do not see the issue any more in the last 2 weeks. I was using the app ~1 hour per day during that time.

If we don't see this coming up anywhere else, it may be a hint to close current issue.

**Comment by GianniCarlo** [comment] 2020-05-31 16:03
> @GianniCarlo Oh, no, than it is unrelated. The crash happens when I'm in playback mode and git the chapter of a single audio book. Can you split this issue or shall I open a new one?

Yeah this is a separate issue, this may be due to the chapter list trying to load the data for books who don't have that metadata 🤔 we should catch those cases and show the empty list

**Comment by GianniCarlo** [comment] 2020-05-31 16:04
> @GianniCarlo Just to keep you informed, I do not see the issue any more in the last 2 weeks. I was using the app ~1 hour per day during that time.
> 
> If we don't see this coming up anywhere else, it may be a hint to close the current issue.

That's great 👌

**Comment by GianniCarlo** [comment] 2020-11-20 21:45
I'm closing this issue since it seems it didn't continue to occur 👍

**Closed by GianniCarlo** 2020-11-20 21:45 UTC
