### ISSUE TITLE
Resume play after calls

### ISSUE THREAD

**Issue by almetria** [TortugaPower/BookPlayer#574] opened 2021-03-21 15:56 UTC
# 🗣 Context

Resume playing after interruptions like when calls end. It isn’t nice having to mess with device after call ends when driving.

**Comment by pichfl** [comment] 2021-03-22 14:14
Do you have an example of an application that actually supports this right now? 

I can't get this working with Apples own apps so I'm fairly certain that there is no way for us to provide this feature as iOS itself is lacking a mechanism for it.

@GianniCarlo may know additional context, but I'll close this for now as it very much seems to be out of our reach 😞

**Closed by pichfl** 2021-03-22 14:14 UTC
Labels: enhancement

**Comment by GianniCarlo** [comment] 2021-03-22 14:35
Hi Guys! we actually have it implemented in the AppDelegate

![Screen Shot 2021-03-22 at 9 31 15 AM](https://user-images.githubusercontent.com/14112819/112006159-76370200-8af1-11eb-87ae-f1104a7bc4ba.png)

The problem is, that sometimes the app can't turn back on the audio session so it can reproduce audio again, when the app enters this state, nothing I've tried have managed to make it able to turn on the audio session, so our current 'fix' is to make the app crash in the background so when it's relaunched again, the OS let's the app turn on the audio session

This problem should happen randomly and not always. Please @almetria can you test if it's always that this happens?

**Comment by almetria** [comment] 2021-03-25 04:58
Pretty much. It’ll be on Bluetooth either car or headphones and won’t resume play once Bluetooth is disconnected. I’m coming from Android/Listen Audiobook Player and your app is the closest I’ve been able to find to it. I can appreciate there are limitations you have to work within. It won’t kill me to have to resume it myself :D
