### ISSUE TITLE
Support for streaming from cloud providers

### ISSUE THREAD

**Issue by NightMachinary** [TortugaPower/BookPlayer#480] opened 2020-07-08 07:18 UTC
Considering that our mobile devices have rather limited storage, and we switch between devices frequently, I feel a strong need to stream audio content from cloud storage (Google Drive, Dropbox, or even a simple HTTP static file server in some cases.). Ideally, the resume information would get saved near the file being played, so it can be played from another device, but just streaming from the cloud is a huge value.

**Comment by pichfl** [comment] 2020-07-08 09:43
This is a duplicate of one of the first issues, #4 to be precise. We did switch to `AVPlayer`, so some progress was made, but we are far from completing this feature.

You describe the playback position sync across devices which we intend to solve in a different matter by syncing meta data between devices through iCloud, using AirDrop and the other transfer mechanisms to transfer the files manually. That way we do not have to implement and continue to support a myriad of file services in BookPlayer, but can rely on their individual apps handling things on their own.

**Closed by pichfl** 2020-07-08 09:43 UTC
Labels: duplicate
